# Generated by Django 2.0.5 on 2018-06-05 14:33

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/frontend/img/octobiwan.jpg', upload_to=base.models.user_directory_path),
        ),
    ]
