# Generated by Django 2.0.5 on 2018-05-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20180522_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.CharField(blank=True, default='/frontend/static/frontend/img/octobiwan.jpg', max_length=255, null=True),
        ),
    ]
