# Generated by Django 2.0.5 on 2018-05-27 21:50

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20180527_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(default='frontend/static/img/octobiwan.jpg', upload_to=base.models.user_directory_path),
        ),
    ]
