# Generated by Django 2.0.5 on 2018-05-28 12:53

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20180527_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='frontend/static/img/octobiwan.jpg', upload_to=base.models.user_directory_path),
        ),
    ]
